### ISSUE TITLE
Write a CLI command to actually download the Album

### ISSUE THREAD

**Issue by Jigar3** [opencodeiiita/albumm#4]
Currently the CLI supports only two commands 
1) Getting User Id from Username
2) List Albums of a particular User

Add Functionality to actually download the Album. Helper Functions have already been created for assistance

**Comment by mendelevium28** [comment]
claim

**Comment by untrulynoxiusmj** [comment]
claim

**Comment by sggts04** [comment]
Can I work on this?

**Comment by Jigar3** [comment]
@sggts04 ya sure go ahead
