### ISSUE TITLE
Write Tests for all functions inside helper.go

### ISSUE THREAD

**Issue by Jigar3** [opencodeiiita/albumm#7]

**Comment by untrulynoxiusmj** [comment]
Claim

**Comment by untrulynoxiusmj** [comment]
@Jigar3  Sir, I am writing tests like this :

![tests](https://user-images.githubusercontent.com/56266286/73463863-fce7c780-43a3-11ea-8cd1-50ec3b5443ec.png)

I want to confirm once if i am doing it correctly

**Comment by Jigar3** [comment]
@untrulynoxiusmj you are going good
